services:
  file-storage-master:
    image: chrislusf/seaweedfs:latest
    ports:
      - "9333:9333"
    hostname: seaweedfs_master
    command: "master -ip=seaweedfs_master -port=9333 -mdir=/data"
    restart: unless-stopped
    environment:
      - PUBLIC_URL=http://localhost:9333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9333/cluster/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - master_data:/data
    networks:
      - app-network
  file-storage-volume:
    image: chrislusf/seaweedfs:latest
    ports:
      - "9000:9000"
    environment:
      - PUBLIC_URL=http:localhost:9000
    hostname: seaweedfs_volume
    command: "volume -dir=/data -publicUrl=localhost:9000 -port=9000 -ip=seaweedfs_volume -mserver=seaweedfs_master:9333"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      file-storage-master:
        condition: service_healthy
    volumes:
      - volume_data:/data
  db:
    image: postgres:16
    container_name: medibrain-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medibrain
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d medibrain || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-network
    restart: always
  migrator:
    image: migrate/migrate:latest
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "host=localhost port=5432 user=root password=1234 dbname=medibrain sslmode=disable",
        "up",
      ]
volumes:
  master_data:
  volume_data:
  db_data:
  qdrant_data:
    driver: local

networks:
  app-network:
    driver: bridge
