services:
  pdf:
    image: stirlingtools/stirling-pdf:1.6.0
    ports:
      - "3000:8080"
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medibrain
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d medibrain || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

volumes:
  db_data:

# Optional but recommended
networks:
  app-network:
    driver: bridge
